apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cgp-database
  name: cgp-database
  namespace: default
spec:
  containers:
    - env:
        - name: APP_DB_NAME
          value: cgpbackbone
        - name: APP_DB_PASS
          value: cgp-pass
        - name: APP_DB_USER
          value: cgp
        - name: POSTGRES_PASSWORD
          value: postgres
      image: postgres:14.2
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        failureThreshold: 5
        periodSeconds: 5
        timeoutSeconds: 5
      name: cgp-database
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /database
          name: cgp-database-cm0
      resources:
          requests:
            cpu: 125m # milicores - equivalent to 12.5% of a single CPU core: 1000m = 1 core = 1 vCPU = 1 GCP Core = 1 AWS vCPU
            memory: 128Mi # mebibits
          limits:
            cpu: 250m # equivalent to 25% of a single CPU core
            memory: 256Mi # mebibits
  restartPolicy: OnFailure
  volumes:
    - configMap:
        name: cgp-database-cm0
      name: cgp-database-cm0
