FROM condorgp:builder

WORKDIR $HOME/code/condorgp

COPY . .

ENV PYENV_GLOBAL=naut_trader
RUN pyenv global ${PYENV_GLOBAL}
ENV PYENV_VERSION=naut_trader

CMD ["python3", "condorgp/comms/run_condorgp/new_condor_run_d.py"]
# CMD ["/bin/bash"]
