FROM condorgp:builder

WORKDIR $HOME/code/condorgp

# create log folder and empty log file, for ease
RUN mkdir /home/user/code/condorgp/condorgp/util/logs/ && \
    touch /home/user/code/condorgp/condorgp/util/logs/condor_log.txt

# create checkpoint folder and empty checkpoint file, for ease
RUN mkdir /home/user/code/condorgp/condorgp/util/checkpoints/ && \
    touch /home/user/code/condorgp/condorgp/util/checkpoints/first_strat_done.pkl

COPY . .

ENV PYENV_GLOBAL=naut_trader
RUN pyenv global ${PYENV_GLOBAL}
ENV PYENV_VERSION=naut_trader

  # python3 condorgp/comms/run_condorgp/cgp_cmd_d.py
CMD ["python3", "condorgp/comms/run_condorgp/cgp_cmd_d.py"]
# CMD ["/bin/bash"]
