#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
EOSQL
# NOTE THIS: ................................
# ...........................................
# CREATE DATABASE IF NOT EXISTS $APP_DB_NAME;

# replaced by, to skip error:

# CREATE DATABASE $APP_DB_NAME;


# IN FACT< TOOK OUT LINE COMPLETELY...





# CHECKLIST OF ABOVE VARIABLES
# ----------------------------
# POSTGRES_PASSWORD
# POSTGRES_USER
# POSTGRES_DB
# APP_DB_USER
# APP_DB_PASS
# APP_DB_NAME
