from typing_extensions import Protocol

class GpProvider(Protocol):
    def set_pset(self, functions: dict, terminals: dict): ...
    def set_gp_fundamentals(self, gp_params: dict): ...
    def set_gp_params(self, params: dict): ...
    def set_evaluator(self, new_evaluator): ...
    def set_pop_size(self, pop_size: int): ...
    def set_gens(self, no_gens: int): ...
    def set_stats(self, stat_params: dict): ...
    def run_gp(self): ...
