services:
  cgp-worker-1:
    container_name: cgp-worker-1
    image: cgp-nt-theirs-plus:latest
    volumes:
      - ../../condorgp:/condorgp
      # python cgp_rabbitmq/delegate/run_delegated_evals_1.py
    # command: ["python", "cgp_rabbitmq/delegate/run_delegated_evals_1.py"]
    # command: ["python", "cgp_rabbitmq/delegate/run_delegated_evals_3_run_naut.py"]
    # command: ["python", "condorgp/evaluation/run_naut.py"]
    # command: ["sh", "scripts/install_cgp_n_run_listener.sh"]
    command: ["/bin/bash"]
    ports:
    - 2271:2271
    environment:
      - IN_DOCKER_COMPOSE=1
    # depends_on:
    #   - cgp-rabbitmq
    # restart: unless-stopped
    networks:
      - cg-net

networks:
  cg-net:
    driver: bridge
