
LEAN_BASE_PATH = '/home/hsth/code/QuantConnect/Lean/'

LEAN_RESULTS_DIR = 'leanQC/results/'
LEAN_ALGOS_DIR = LEAN_BASE_PATH + 'Algorithm.Python/'
LEAN_LAUNCHER_DIR = 'Launcher/bin/Debug/'
LEAN_CONFIG_DIR = LEAN_BASE_PATH + LEAN_LAUNCHER_DIR
LEAN_SOURCE_CONFIG_FILE = 'leanQC/config/config.json'

lean_dict = {
    'LEAN_SOURCE_CONFIG_FILE': LEAN_SOURCE_CONFIG_FILE,
    'LEAN_LAUNCHER_DIR': LEAN_LAUNCHER_DIR,
    'LEAN_CONFIG_FOLDER': LEAN_CONFIG_DIR,
    'LEAN_ALGOS_FOLDER': LEAN_ALGOS_DIR,
    'LEAN_RESULTS_FOLDER': LEAN_RESULTS_DIR,
    'REASONABLE_FITNESS_SECS': 60,
    }

CONDOR_TEST_ALGOS_DIR = 'tests/resources/'

test_dict = {
    'CONDOR_TEST_ALGOS_FOLDER': CONDOR_TEST_ALGOS_DIR,
    }
