apiVersion: v1
kind: ConfigMap
metadata:
  name: cgp-config
  namespace: cgp-system
data:
  POSTGRES_DATABASE_URL: "postgresql+psycopg2://cgp:cgp_pass@cgp-database:5432/cgpbackbone"
  APP_DB_PASS: ${APP_DB_PASS}
  APP_DB_USER: ${APP_DB_USER}
  APP_DB_NAME: ${APP_DB_NAME}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${APP_DB_NAME}
