"""populations table

Revision ID: 3896be6c765b
Revises: b5068779a6c1
Create Date: 2025-03-16 15:30:33.351850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3896be6c765b'
down_revision: Union[str, None] = 'b5068779a6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('populations',
    sa.Column('pop_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pop_name', sa.String(), nullable=False),
    sa.Column('pop_start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('num_gens', sa.Integer(), nullable=False),
    sa.Column('pop_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pop_id')
    )
    op.add_column('individuals', sa.Column('ind_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('individuals', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individuals', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('individuals', 'ind_id')
    op.drop_table('populations')
    # ### end Alembic commands ###
