"""changes to individuals schema for pydantic v2

Revision ID: 50b4d39b1e33
Revises: 6a8c342f3321
Create Date: 2025-01-28 09:51:35.553557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b4d39b1e33'
down_revision: Union[str, None] = '6a8c342f3321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
