"""added individuals table

Revision ID: 6a8c342f3321
Revises: a6f3a1d1b6c9
Create Date: 2025-01-27 21:58:52.131072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a8c342f3321'
down_revision: Union[str, None] = 'a6f3a1d1b6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individuals',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_date_logged', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_fit_run_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fit_run', sa.Boolean(), nullable=False),
    sa.Column('fitness', sa.Float(), nullable=False),
    sa.Column('ind_string', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individuals')
    # ### end Alembic commands ###
