"""full restart

Revision ID: 6dfd967bd9dc
Revises: 
Create Date: 2025-03-17 09:16:38.473441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dfd967bd9dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('populations',
    sa.Column('pop_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pop_name', sa.String(), nullable=False),
    sa.Column('pop_start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('num_gens', sa.Integer(), nullable=False),
    sa.Column('pop_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pop_id')
    )
    op.create_table('individuals',
    sa.Column('ind_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_date_logged', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_fit_run_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fit_run', sa.Boolean(), nullable=False),
    sa.Column('fitness', sa.Float(), nullable=False),
    sa.Column('ind_string', sa.TEXT(), nullable=False),
    sa.Column('pop_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['pop_id'], ['populations.pop_id'], ),
    sa.PrimaryKeyConstraint('ind_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individuals')
    op.drop_table('populations')
    op.drop_table('comms')
    # ### end Alembic commands ###
