"""x2 changes to individuals schema for pydantic v2

Revision ID: 8c5054edef1f
Revises: 50b4d39b1e33
Create Date: 2025-01-28 10:24:27.932385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5054edef1f'
down_revision: Union[str, None] = '50b4d39b1e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
