"""basic comms table

Revision ID: a6f3a1d1b6c9
Revises: 
Create Date: 2025-01-18 20:30:53.901425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f3a1d1b6c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comms')
    # ### end Alembic commands ###
