"""adj foreign key individuals to populations pop_id 1

Revision ID: c6021a6c4f31
Revises: 6dfd967bd9dc
Create Date: 2025-03-17 09:20:46.454842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6021a6c4f31'
down_revision: Union[str, None] = '6dfd967bd9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
