"""foreign key pop_id in individuals table 3

Revision ID: c7977b00ac20
Revises: fddcea0eb245
Create Date: 2025-03-16 15:45:25.011479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7977b00ac20'
down_revision: Union[str, None] = 'fddcea0eb245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individuals', sa.Column('population_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'individuals', 'populations', ['population_id'], ['pop_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'individuals', type_='foreignkey')
    op.drop_column('individuals', 'population_id')
    # ### end Alembic commands ###
