"""foreign key pop_id in individuals table

Revision ID: cea91f2f3c2e
Revises: 3896be6c765b
Create Date: 2025-03-16 15:42:10.269792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea91f2f3c2e'
down_revision: Union[str, None] = '3896be6c765b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
