"""foreign key pop_id in individuals table 2

Revision ID: fddcea0eb245
Revises: cea91f2f3c2e
Create Date: 2025-03-16 15:43:23.284066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddcea0eb245'
down_revision: Union[str, None] = 'cea91f2f3c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
