FROM vsc-basic-python-7a94d97c7e4ae30dc4170673c9f8c8992e1b9f31abebe48ebc3675d5c971eeb6:latest AS cgp_dev

# ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# set TERM
ENV TERM=xterm-256color

ENV IN_DOCKER_COMPOSE=0

ENV ON_K8S_CLUSTER=1


# set location to avoid hang on tzdata
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV PYTHON_VERSION 3.12.0
# but installed previously

RUN apt update

WORKDIR /condorgp

COPY ./ ./

RUN pip install poetry==1.8.4

RUN poetry install


CMD ["/bin/bash"]
