FROM python:3.8.14-slim

#Do not use env as this would persist after the build and would impact your containers, children images
ARG DEBIAN_FRONTEND=noninteractive

# force the stdout and stderr streams to be unbuffered.
ENV PYTHONUNBUFFERED 1

#Setup workdir
WORKDIR /cgp_api

COPY ../cgp_api  ./

RUN apt-get update \
    && apt-get -y upgrade \
    && pip install --no-cache-dir poetry \
    && poetry install \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8000

ENTRYPOINT [ "poetry", "run" ]

CMD ["uvicorn", "tweets_api.main:app", "--host", "0.0.0.0", "--port", "8000"]

#size: 143MB
