FROM cgp-nt-again:latest AS cgpstar

# ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# set TERM
ENV TERM=xterm-256color

ENV IN_DOCKER_COMPOSE=0

ENV ON_K8S_CLUSTER=1


# set location to avoid hang on tzdata
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# always:
# RUN apt-get update


ENV PYTHON_VERSION 3.12.0
# but installed previously

# RUN apt-get update \
#   && apt-get install -y  \
#     libbluetooth-dev \
#     tk-dev \
#     uuid-dev \
#     apt-transport-https \
#     jq \
#     unzip \
#     curl \
#     wget \
#     git \
#     vim \
#     virtualenv \
#     python3-pip \
#     zsh \
#     tree \
#     gh \
#     libgdbm-dev \
#     libc6-dev \
#     libbz2-dev \
#     build-essential \
#     net-tools \
#     iproute2 \
#     iputils-ping \
#     direnv \
#     # python support packages
#     make \
#     libssl-dev \
#     zlib1g-dev \
#     libbz2-dev \
#     libreadline-dev \
#     libsqlite3-dev \
#     llvm \
#     libncursesw5-dev \
#     # xz-utils
#     tk-dev \
#     libxml2-dev \
#     libffi-dev \
#     liblzma-dev \
#     python3-dev \
#     libncurses5-dev \
#   && apt-get clean

# RUN pip3 install numpy setuptools wheel six auditwheel poetry==1.8.4

# NOTE:
  # all the above were previously installed, see FROM above


# all the below to install VS Code,
#   but where using as a dev container, not needed?

# #######################################################################
# @@@
# #######################################################################

# RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg

# RUN install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/

# RUN sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'

# RUN rm -f packages.microsoft.gpg

# RUN apt update

# RUN apt install -y code



CMD ["/bin/bash"]
