[tool.poetry]
name = "tweets-sharding"
version = "0.1.0"
description = ""
authors = ["Oliver Giles <ogiles@email.com>"]
packages = [{include = "tweets_api"}]

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = "^1.4.42"
psycopg2-binary = "^2.9.5"
python-dotenv = "^0.21.0"
pydantic = "^1.10.2"
fastapi = "^0.86.0"
uvicorn = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
