kind: Service
apiVersion: v1
metadata:
  name: cgp-ingress-service
spec:
  type: LoadBalancer
  selector:
    app: cgp-database
  ports:
  - protocol: TCP
    name: service-port
    port: 80
    targetPort: 5432
