apiVersion: v1
kind: PersistentVolume
metadata:
  name: cgp-database-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /database
  storageClassName: standard



