apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgp-database-volume-claim
  namespace: default
  labels:
    app: cgp-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
