apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cgp-database-statefulset
  namespace: default
  labels:
    app: cgp-database
spec:
  replicas: 1

  selector:
    matchLabels:
      app: cgp-database

  serviceName: "cgp-database"
  template:
    metadata:
      labels:
        app: cgp-database
    spec:
      containers:
        - name: cgp-database
          image: postgres:14.2
          env:
            - name: APP_DB_NAME
              value: cgpbackbone
            - name: APP_DB_PASS
              value: cgp-pass
            - name: APP_DB_USER
              value: cgp
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
              name: port-cgp-db
              protocol: TCP
          volumeMounts:
            - name: cgp-database-mount
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 125m # milicores - equivalent to 12.5% of a single CPU core: 1000m = 1 core = 1 vCPU = 1 GCP Core = 1 AWS vCPU
              memory: 128Mi # mebibits
            limits:
              cpu: 250m # equivalent to 25% of a single CPU core
              memory: 256Mi # mebibits
      volumes:
        - name: cgp-database-mount
          persistentVolumeClaim:
            claimName: cgp-database-volume-claim
        - name: cgp-database-cm0
          configMap:
            name: cgp-database-cm0
