apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cgp-grafana
  name: cgp-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cgp-grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cgp-grafana
    spec:
      containers:
        - env:
            - name: AMQP_URL
              valueFrom:
                configMapKeyRef:
                  key: AMQP_URL
                  name: env
            - name: APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_DB_NAME
                  name: env
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASS
              value: admin
            - name: OVERLAY_NETWORK
              valueFrom:
                configMapKeyRef:
                  key: OVERLAY_NETWORK
                  name: env
            - name: PIKA_URL_MANUAL
              valueFrom:
                configMapKeyRef:
                  key: PIKA_URL_MANUAL
                  name: env
            - name: POSTGRES_DATABASE_URL
              value: postgresql+psycopg2://cgp:cgp-pass@cgp-database:5432/cgp-backbone
          image: grafana/grafana-enterprise
          name: cgp-grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 125m # milicores - equivalent to 12.5% of a single CPU core: 1000m = 1 core = 1 vCPU = 1 GCP Core = 1 AWS vCPU
              memory: 128Mi # mebibits
            limits:
              cpu: 250m # equivalent to 25% of a single CPU core
              memory: 256Mi # mebibits
          volumeMounts:
            - mountPath: /grafana_data
              name: cgp-grafana-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: cgp-grafana-cm0
          name: cgp-grafana-cm0
