apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: cgp-rabbitmq
  name: cgp-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cgp-rabbitmq
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: cgp-rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          image: rabbitmq:3.13-management
          name: cgp-rabbit
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          resources:
            requests:
              cpu: 125m # milicores - equivalent to 12.5% of a single CPU core: 1000m = 1 core = 1 vCPU = 1 GCP Core = 1 AWS vCPU
              memory: 128Mi # mebibits
            limits:
              cpu: 250m # equivalent to 25% of a single CPU core
              memory: 256Mi # mebibits
      restartPolicy: Always
