apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cgp-ingress
spec:
  rules:
  - host: k8s.cgp.database.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cgp-database
            port:
              number: 5432
